repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.3
    hooks:
      - id: ruff
  - repo: local
    hooks:
      - id: validate-config
        name: Validate config
        entry: python config/config_validator.py
        language: system
        pass_filenames: false
