name: mobile_jarvis_ui
description: Jarvis-like HUD for Mercurius∞
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  rive: ^0.13.20
  flutter_tts: ^4.2.3
  flutter_sound: ^9.2.13
  speech_to_text: ^7.0.0
  permission_handler: ^12.0.0+1
  connectivity_plus: ^6.1.4
  network_info_plus: ^6.1.4
  wifi_scan: ^0.4.0
  animated_background: ^2.0.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
