name: mobile_jarvis_ui
description: Jarvis-like HUD for Mercurius∞
version: 0.1.0
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  rive: ^0.11.17
  flutter_tts: ^3.7.0
  flutter_sound: ^9.2.13
  speech_to_text: ^5.8.0
  permission_handler: ^10.4.3
  connectivity_plus: ^5.0.2
  network_info_plus: ^4.0.1
  wifi_scan: ^2.0.4
  animated_background: ^2.0.0
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - assets/
