agents:
  enabled: ["OPENAI", "OLLAMA", "AZR"]

communication:
  feedback_loop: true
  max_retries: 3
  retry_delay: 2

mission_defaults:
  run_mode: dialogic-autonomous
  tasks:
    - "#SELF_MISSION"
    - "#RUN_SELF_CHECK"

paths:
  transcripts: "memory/transcripts/"
  logs: "logs/"
